// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var SHOPIFY_DOMAIN = "str4c2-32.myshopify.com";
var SHOPIFY_API_VERSION = "2025-07";
var list_products_default = defineTool({
  name: "list_products",
  title: "List Punarvsu products",
  description: "List currently available handcrafted bags from Punarvsu (sacred temple textile upcycled products). Returns title, handle, price, availability and product URL.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of products to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const token = process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN;
    if (!token) {
      return {
        content: [{ type: "text", text: "Shopify Storefront token not configured." }],
        isError: true
      };
    }
    const query = `{
      products(first: ${limit ?? 20}) {
        edges { node {
          title handle description availableForSale
          priceRange { minVariantPrice { amount currencyCode } }
        } }
      }
    }`;
    const resp = await fetch(
      `https://${SHOPIFY_DOMAIN}/api/${SHOPIFY_API_VERSION}/graphql.json`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Shopify-Storefront-Access-Token": token
        },
        body: JSON.stringify({ query })
      }
    );
    if (!resp.ok) {
      return {
        content: [{ type: "text", text: `Shopify error: ${resp.status}` }],
        isError: true
      };
    }
    const data = await resp.json();
    const products = (data?.data?.products?.edges ?? []).map((e) => {
      const n = e.node;
      const p = n.priceRange.minVariantPrice;
      return {
        title: n.title,
        handle: n.handle,
        price: `${p.currencyCode} ${p.amount}`,
        available: n.availableForSale,
        url: `https://punarvsu.com/product/${n.handle}`,
        description: (n.description || "").slice(0, 200)
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var SHOPIFY_DOMAIN2 = "str4c2-32.myshopify.com";
var SHOPIFY_API_VERSION2 = "2025-07";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch full details for a single Punarvsu product by its handle (slug). Includes description, variants, price and images.",
  inputSchema: {
    handle: z2.string().min(1).describe("Product handle/slug, e.g. 'temple-tote'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ handle }) => {
    const token = process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN;
    if (!token) {
      return {
        content: [{ type: "text", text: "Shopify Storefront token not configured." }],
        isError: true
      };
    }
    const query = `query($handle: String!) {
      productByHandle(handle: $handle) {
        title handle description availableForSale
        priceRange { minVariantPrice { amount currencyCode } }
        images(first: 5) { edges { node { url altText } } }
        variants(first: 10) { edges { node { title availableForSale price { amount currencyCode } } } }
      }
    }`;
    const resp = await fetch(
      `https://${SHOPIFY_DOMAIN2}/api/${SHOPIFY_API_VERSION2}/graphql.json`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Shopify-Storefront-Access-Token": token
        },
        body: JSON.stringify({ query, variables: { handle } })
      }
    );
    if (!resp.ok) {
      return {
        content: [{ type: "text", text: `Shopify error: ${resp.status}` }],
        isError: true
      };
    }
    const data = await resp.json();
    const p = data?.data?.productByHandle;
    if (!p) {
      return {
        content: [{ type: "text", text: `No product found with handle '${handle}'.` }],
        isError: true
      };
    }
    const product = {
      title: p.title,
      handle: p.handle,
      description: p.description,
      available: p.availableForSale,
      price: `${p.priceRange.minVariantPrice.currencyCode} ${p.priceRange.minVariantPrice.amount}`,
      url: `https://punarvsu.com/product/${p.handle}`,
      images: p.images.edges.map((e) => ({ url: e.node.url, alt: e.node.altText })),
      variants: p.variants.edges.map((e) => ({
        title: e.node.title,
        available: e.node.availableForSale,
        price: `${e.node.price.currencyCode} ${e.node.price.amount}`
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/brand-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var brand_info_default = defineTool3({
  name: "brand_info",
  title: "About Punarvsu",
  description: "Returns Punarvsu brand information: mission, sacred textile process, artisan team, contact and shipping details. Use for questions about the brand's story, ethics, or how to reach them.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      brand: "Punarvsu",
      tagline: "India's first brand making luxury bags from sacred temple textiles (Bhagwan ki Poshak).",
      workshop: "Maharana Pratap Community Centre, Sector-9, Rohini, Delhi 110085",
      managed_by: "Sampurna NGO (35+ years of social work)",
      head_artisan: "Kiran Mam (women-led team)",
      temple_partners: ["Khatushyam Delhi Dham", "other Delhi & North India temples"],
      impact: {
        sacred_textile_saved_kg: 3200,
        hours_per_piece: "8-15 hours handcrafted, UV sterilized, no machines"
      },
      shipping: "Free above \u20B95,000 | Ships across India | 5-10 business days",
      returns: "No returns \u2014 each bag carries sacred temple blessings",
      contact: {
        email: "punarvsu.com@gmail.com",
        phone: "+91-9220464425",
        website: "https://punarvsu.com"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "punarvsu-mcp",
  title: "Punarvsu",
  version: "0.1.0",
  instructions: "Tools for Punarvsu \u2014 sacred temple-textile handcrafted bags. Use `list_products` to browse the live catalog, `get_product` for full details on a specific bag by handle, and `brand_info` for brand story, artisans, shipping and contact.",
  tools: [list_products_default, get_product_default, brand_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
